# -*- coding: utf-8 -*-
"""image_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ParitoshThakur-07/MyCaptain/blob/main/image_classification.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
# %matplotlib inline

data = pd.read_csv('mnist.csv')

data.head()

a = data.iloc[3,1:].values

a = a.reshape(28,28).astype('uint8')
plt.imshow(a)

df_x = data.iloc[:,1:]
df_y = data.iloc[:,0]

x_train , x_test, y_train, y_test = train_test_split(df_x,df_y,test_size = 0.2, random_state =4)

y_train.head()

rf = RandomForestClassifier(n_estimators=100)

clf = HistGradientBoostingClassifier()
clf.fit(x_train,y_train)

pred = clf.predict(x_test)

pred

s = y_test.values

count = 0
for i in range(len(pred)):
  if pred[i] == s[i]:
    count = count + 1

count

len(pred)

(645/689) * 100

